### ISSUE TITLE
ForgeMultipart-1.10.2-2.0.0.31-universal : rendering issues on microblocks

### ISSUE THREAD

**Issue by UnixRonin** [TheCBProject/ForgeMultipart#12] opened 2017-04-27 19:51 UTC
I am seeing bizarrely distorted rendering glitches on microblocks. At first I thought this was only occurring with OptiFine, but have since observed it without OptiFine as well.  See 
https://www.caerllewys.net/public/minecraft/2017-04-22_18.02.21.png for an example of the problem.  (Note that the screenshot was taken with OptiFine and shaders in use, but the same problem occurs with no shaderpack and without OptiFine at all.)

**Comment by crosenquist** [comment] 2017-06-02 05:02
I too am experiencing this rendering issue. The more microblocks that I use, the worse it appears to become.

**Comment by covers1624** [comment] 2017-06-02 08:45
I've managed to reproduce this in dev and I can confirm something funky is happening, this will likely be fixed with 1.11's rewrite to part rendering.

**Comment by crosenquist** [comment] 2017-06-03 05:44
I see. Glad to know that you're able to reproduce this internally! I'm not sure how large the task of refactoring the part rendering system is, but would it be correct to expect that 1.10.2 will not be receiving this fix?

**Comment by Electro-ninja** [comment] 2017-06-03 05:46
Oh, I have this bug aswell. Also if 1.10.2 does concurrently get fixed through your efforts you would be considered "The awesomest modder on the planet" for the day, at least in my opinion.

http://i.imgur.com/08CWOu0.png

**Comment by Kundello** [comment] 2017-07-09 01:58
Sooo, can it been fixed in 1.10.2? Our team really can't migrate a whole server platform with mods and plugins to 1.11, but we also can't disable Forge Multipart in our project, because its a core mod for our architecture server, and this bug makes all buildings collapsed :C

**Comment by covers1624** [comment] 2017-07-09 02:00
I'm going to be pushing 1.11 builds soon so when it's fixed if its simple ill pull it back.

**Comment by Electro-ninja** [comment] 2017-07-13 22:32
You are a gentleman and a scholar Mr. Covers.

**Comment by covers1624** [comment] 2017-07-20 16:29
This is now fixed and has been back ported to 1.10.

**Closed by covers1624** 2017-07-20 16:29 UTC
