### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by JoeSGT** [TheCBProject/ForgeMultipart#26] opened 2018-06-15 02:09 UTC
https://pastebin.com/raw/TK7aAutt
i got this crash report is related to this crash i am unsure how to reproduce it but can you fix it please and thanks you

EDIT: it's getting annoying now i have 20 of these same crash reports and it's getting annoying having the server crash more the 5 times, if this is already fix can you post the commit ? I had also tried `2.4.2.59` but didn't fix the issue

**Comment by covers1624** [comment] 2018-06-15 04:30
You opened this 30 miniutes ago, a discord pm was not nessesary just to tell me how annoying it is, secondly, search the other issues first, this is a Duplicate of https://github.com/TheCBProject/ForgeMultipart/issues/18

**Closed by covers1624** 2018-06-15 04:30 UTC
