### ISSUE TITLE
Constant console spam with Sponge

### ISSUE THREAD

**Issue by TheOpalium** [TheCBProject/ForgeMultipart#33] opened 2018-07-17 08:43 UTC
Hello.

There seems to be an issue running this mod together with Sponge.
Minecraft v1.12.2, Forge 14.23.4.2735, Sponge 7.1.0-3304, ForgeMultipart 1.12.2-2.4.2.60

I'm getting the following errors constantly spamming in my server console:

> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1792, y=12, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1786, y=10, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1778, y=5, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1779, y=5, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1787, y=11, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1782, y=6, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1785, y=9, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1789, y=12, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1783, y=7, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1780, y=5, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1788, y=11, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1
> [04:41:09] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=Survival, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-1791, y=12, z=-733}, blockMetadata=-1} - class class TileMultipart_cmp$$1

Basically, these show up every minute or so for every single ForgeMultipart entity in the world. while there are no actual problems, this makes using the console an absolute nightmare with these constantly popping up.

Any ideas on how to stop this?
~Opalium

**Comment by covers1624** [comment] 2018-07-22 20:18
Sponge likely doesn't like the registry wrapping FMP has to do. Not sure if there is much i can do.

**Comment by codydbgt** [comment] 2018-07-22 22:32
this fixed the issue all my pipes repaired 
 mod:projectred-transportation -> fmp

**Comment by covers1624** [comment] 2018-07-22 22:39
Your reply makes no sense.

**Comment by codydbgt** [comment] 2018-07-22 23:15
ProjectRedRelocation.cfg

**Comment by covers1624** [comment] 2018-07-22 23:15
That has absolutely nothing to do with this..

**Comment by codydbgt** [comment] 2018-07-22 23:18
my issue was closed makred as a dupe so i came here

**Comment by covers1624** [comment] 2018-07-23 00:45
Ahh i see, appologies but the wording of your issue was poor, regardless, you seem to have fixed your issue and the log pieces you posted are a duplicate of this issue.

**Comment by TheOpalium** [comment] 2018-07-23 07:44
@codydbgt  We're you having the same issue as this one? If so, can you explain in more detail how you fixed it? I can't understand it from your reply.

**Comment by covers1624** [comment] 2018-07-23 07:46
No, this is just console spam it can technically be ignored, he did not fix this issue, his initial report was unclear and incomplete, the log segment he provided was this issue. What his /actual/ issue was, i have no idea, but he seemed to fix it himself.

**Comment by Slayer5934** [comment] 2018-07-23 18:38
I can verify its definitely a sponge issue.

**Comment by codydbgt** [comment] 2018-07-23 20:03
it turns out i didnt fix it :/ so sad :( but this issue is the same one i had and isnt a project red issue it is a sponge issue that effect many TE and that spam is them not being loaded right or at all

**Comment by gabizou** [comment] 2018-07-26 17:20
@covers1624 it isn't really fixed, it's just ~silenced~ ignored. I think it's still a fundamental issue that the registration can't be found through forge registries. 

The lookup for Sponge is based on the add hooks from Forge for the entity list registration, and for the hooks in TileEntity registration. Why they are not showing up as being created is likely because they aren't exposed to the normal registries, which in this case, led to the spam.

Perhaps if you could explain how to go from an `Entity` or `TileEntity` instance to a `ResourceLocation` for the id that would be used for serialization, that would make it easier for us to make it work in sponge.

**Comment by covers1624** [comment] 2018-07-26 22:46
Ah, sure. Fmp wraps the tile registry so I can have duplicate class -> ResourceLocation mappings, as fmp dynamically constructs tile classes with mixins applied. Sponge might be grabbing a reference to the registry before I wrap it.

**Comment by gabizou** [comment] 2018-07-26 23:31
Since 90% of Sponge's code is in what we call "SpongeCommon", we used the method for vanilla's TileEntity registration:

https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/tileentity/MixinTileEntity.java#L136

It's pretty simple, and does it's job to catch forge's modifications for registrations, but we have not considered needing to use an alternative registry point for tile entities.

**Comment by covers1624** [comment] 2018-07-27 08:10
I'm not too sure there is anything i can do for this my side, by wrapping the registry i keep compatibility with anyone querying the registry like normal, be that with the Registry instance directly or with `TileEntity.getKey`. What exactly is the point of sponge sniffing registrations like that? Shouldn't TileEntity.geyKey be enough? What is the sniffed data used for?

**Comment by covers1624** [comment] 2018-07-31 09:39
No problem!, and Yes, see [Here](https://github.com/TheCBProject/ForgeMultipart/blob/master/src/main/scala/codechicken/multipart/DuplicateValueRegistry.java) for the registry, and [Here](https://github.com/TheCBProject/ForgeMultipart/blob/master/src/main/scala/codechicken/multipart/WrappedTileEntityRegistry.scala#L36) for a more indepth explanation i wrote up ages ago. Please mind your step, the code is a little messy..

**Comment by gabizou** [comment] 2018-07-31 20:45
[spongeforge-1.12.2-2705-7.1.0-tile-entity-test1.jar.zip](https://github.com/TheCBProject/ForgeMultipart/files/2247026/spongeforge-1.12.2-2705-7.1.0-tile-entity-test1.jar.zip)
I've modified our tile entity type requests to use the registry query in forge environments. Can someone test that this doesn't spam with the modified registry from FMP?

**Comment by TheOpalium** [comment] 2018-08-01 21:35
@gabizou I will test this on my server and let you know. Thank you for your help!

**Comment by TheOpalium** [comment] 2018-08-07 17:57
Sorry for the wait. I have tested this build and no errors are showing anymore.
Whatever you did, it worked. Thank you @gabizou.

**Comment by covers1624** [comment] 2018-08-22 06:33
I'm going to close this now, Sponge has _actually_ implemented a fix.

**Closed by covers1624** 2018-08-22 06:33 UTC
