### ISSUE TITLE
Multipart tiles improperly loading on chunk load.

### ISSUE THREAD

**Issue by covers1624** [TheCBProject/ForgeMultipart#29] opened 2018-06-28 04:40 UTC
I'm collating this issue from ProjectRed and Translocators into one issue.

Basically on Chunkload Multipart tiles fail to load, it is unclear if they fail on the client AND server, i have not received a clear answer on this.

Please no `I am getting this too!` comments, only constructive comments providing data towards tracking this down, i.e examples of this only being a client side issue, nbt dumps on the block server side whilst its not existing on the client.

**Comment by lonyelon** [comment] 2018-06-28 12:40
It is both, on server and client

**Comment by marcin212** [comment] 2018-06-28 13:57
I'm not sure if this helps, but in the screenshot where the Light Overlay mod doesn't show any number there were ProjectRed tubes. They disappeared when we all left the server and came back after a few hours. In those places blocks could be placed without issue.

![Screenshot](https://img.bymarcin.com/2018-06-27_18-27-19_ZU07Xp4pCdwd8qOL.png)

**Comment by SirDavidIII** [comment] 2018-06-29 20:41
Used versions (As part of FTB Revelations 2.1.0):
ProjectRed-1.12.2-4.9.1.92-lighting
ForgeMultipart-1.12.2-2.4.2.60-universal

More screenshots regarding this issue with light sources [here](https://imgur.com/a/6Wo2PW5)

This bug happens only on dedicated server, when I load the save in singleplayer everything works. If I replace all disappearing blocks in singleplayer, where they work, they will still disappear on server. Tinkering with video settings and video card yielded no results.

**Comment by Frosthaven** [comment] 2018-07-11 02:31
Getting a report from one of my users. Upon questioning him thoroughly, alloy wires vanished upon server restart. However, redstone signal was still being processed as if the wires were still there.

Unlike previous reports, trying to place a block where the ghost wires are deletes the block immediately.

**Comment by marcin212** [comment] 2018-07-12 15:04
@covers1624 Still does not work.
Before:
![pre](https://img.bymarcin.com/2018-07-12_16-53-17_KKNtpBWfakqdSWNr.png)
After:
![after](https://img.bymarcin.com/2018-07-12_16-57-15_ptWJpqA0bPIIboC2.png)

**Comment by covers1624** [comment] 2018-07-12 19:05
Noted, Thanks.

**Comment by seancrain** [comment] 2018-07-13 04:15
I can confirm that this issue is very, very strange.

So, over the last few days, I've been working on a new door system and some lighting for NosLabs, which is my friends and I's own custom version of YogLabs. I've repeatedly had to place the wires back in after the doors failed to function.

However, I logged into the server after restarting it, and the blocks that had disappeared were suddenly back. I cannot say that the new release of Multipart fixed it, but I do know that these blocks were there, then they disappeared, then they came back.

Lanterns that reappeared:
![ProjectRed Lanterns that reappeared:](https://i.imgur.com/v688cgF.png)

Wires that reappeared, making malfunctioning door functional again:
![Wires that reappeared, making malfunctioning door functional again:](https://i.imgur.com/eVpaMi5.png)

Yet, somehow, right next door to the wires that went haywire, the microblocks utilized in the design have never once disappeared.

![Microblocks that work correctly](https://i.imgur.com/nySwLn3.png)

**Comment by covers1624** [comment] 2018-07-13 10:15
Interesting, it sounds like multiparts are failing to load /sometimes/ but no data is actually lost, i'm still unable to reproduce this in dev, but i will write something up to debug this more, half the reports seem to indicate only the client has issues, i.e, wires still work and others indicate that they don't exist on the client. I suspect the version i linked above may have fixed the destroying of the parts.

**Comment by lonyelon** [comment] 2018-07-13 11:19
When using the version @covers1624 provided the bug seems fixed to me.

**Comment by seancrain** [comment] 2018-07-13 17:44
I will let you know if anything disappears again when I get on later.

**Comment by AutoJukebox** [comment] 2018-07-16 21:09
Same issue on 1.12 - 4.9.1.92

**Comment by seancrain** [comment] 2018-07-23 18:58
The new build of Forge Multipart, 1.12.2-2.4.2.63, continues to suffer this bug. If you attempted to fix it in that build, it didn't correct itself.

Come to think of it, I don't know if anyone has tested this without FoamFix installed. Add the anarchy build of FoamFix to your development environment and see if that has anything to do with it. It might be a performance enhancing mod breaking something no one's expecting.

**Comment by seancrain** [comment] 2018-07-24 07:45
I will do some tests as soon as I can.

Also, @asiekierka is the developer of FoamFix. I'll get his attention to see if he knows what might be causing it, if it is a FoamFix issue.

**Comment by covers1624** [comment] 2018-07-24 07:48
I seriously doubt its anything in FoamFix, it'd have to touch how onLoad works with tiles, or break the registry wrapping i do for tiles. I've looked through it and i cant see anything that touches TileEntity.onLoad, and it isn't breaking the registry wrapping as the issue is intermittent. But if asie has any thoughts on something in FoamFix that could cause this, im all ears.

**Comment by asiekierka** [comment] 2018-07-24 07:54
First try coremod.forceDisable=true. If that helps, I'd bet coremod.fasterHopper, coremod.fasterPropertyComparisons, coremod.smallPropertyStorage could be ones which might do something which affects it, but I think it's unlikely.

**Comment by asiekierka** [comment] 2018-07-24 07:54
You may find this handy for debugging coremod modifications: https://asie.pl/files/mods/EnvironmentChecker/environmentchecker-0.1.2.jar

**Comment by seancrain** [comment] 2018-07-24 08:13
What version of Forge do you guys compile against in development environments? I was scrolling through the Forge changelogs and noticed this:

Build 1.12.2-14.23.3.2655:
	LexManos: Bump Forge version for new dev chunk.

Knowing that 1.13 changed the way that chunks work by eliminating the rest of the old numerical block ID system, is it plausible that something was applied in this or around this build of Forge that modified the world save code that Multipart didn't like?

I'm not a Java expert, but knowing that this is a chunk issue, I want to make sure that something like this isn't overlooked.

**Comment by covers1624** [comment] 2018-07-24 08:18
No? We are still in 1.12.. Forge hasn't changed anything regarding tile loading in a long time.
This is likely a race condition /somewhere/. Currently putting together a build with some old logic for tile loading, this bug likely originated from me being /too/ smart with part loading and attempting to support WE / frames. I'll have to come up with another solution for that.

**Comment by covers1624** [comment] 2018-07-24 08:20
Also, thanks Asie for your input. I highly doubt FF is contributing to the issue, but best to cover all bases.

**Comment by seancrain** [comment] 2018-07-24 08:21
I brought it up because I saw "dev chunk" and the first thing to came to mind was Applied Energistics making a transfer version between 1.6.4 and 1.7.2 way, way back in 2014, so I thought it may've been a slight change in preparation for something.

**Comment by asiekierka** [comment] 2018-07-24 08:32
I think "dev chunk" means "chunk of development", not a literal Minecraft chunk.

**Comment by covers1624** [comment] 2018-07-24 08:36
Please test: https://cdn.discordapp.com/attachments/159971888485892096/471232431865724928/ForgeMultipart-1.12.2-2.4.2.null-universal.jar

**Comment by seancrain** [comment] 2018-07-24 08:53
@asiekierka That should've clicked, but it didn't.

@covers1624 It's 4 AM here. I'd test it now but I'm about to fall asleep in my chair.

**Comment by covers1624** [comment] 2018-07-24 10:18
Committed my changes. Should also support WorldEdit now. http://chickenbones.net/maven/codechicken/ForgeMultipart/1.12.2-2.4.2.64/ Please test.

**Comment by seancrain** [comment] 2018-07-24 20:12
@covers1624 I installed build 65, and every wire on the server is back, as are the microblocks. I'll let you know if it begins to malfunction later.

**Comment by seancrain** [comment] 2018-07-26 01:38
@covers1624 , I can report that the server has been up without issues for nearly two days. You can close this issue if you like

**Comment by covers1624** [comment] 2018-07-26 01:40
Thanks for the testing, ill leave this marked as fixed in dev and open until i release the fix on curse, just waiting on feedback for some other things.

**Closed** 2018-07-29 07:30 UTC
Labels: bug, fixed
